example.app:
  db:
    name: 'example_app'

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: basic

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web.exposure:
      include: '*'